# Site settings
title: "5818-Doc 2.0"
baseurl: "/Primary"
url: "https://team5818.github.com"

# Build settings
markdown: CommonMarkGhPages
permalink: /:categories/:year/:month/:day/:title

commonmark:
  options: []
  extensions: ["table"]
